### ISSUE TITLE
IndexError: The shape of the mask [7] at index 0 does not match the shape of the indexed tensor [8, 1536] at index 0

### ISSUE THREAD

**Issue by liuyangyu2003** [drboog/Shifted_Diffusion#14]
hi, how can I solove this problem?
Steps:  34%|█████████████████████████████████████████████████▋                                                                                              | 10347/30000 [3:03:01<5:47:44,  1.06s/it, lr=1e-5, step_loss=0.158]Traceback (most recent call last):
  File "finetune.py", line 869, in <module>
    main()
  File "finetune.py", line 799, in main
    encoder_hidden_states[clip_empty_idx] = empty_emb[clip_empty_idx]
IndexError: The shape of the mask [7] at index 0 does not match the shape of the indexed tensor [8, 1536] at index 0

**Comment by rutuja1409** [comment]
Hey @liuyangyu2003 were

> hi, how can I solove this problem? Steps: 34%|█████████████████████████████████████████████████▋ | 10347/30000 [3:03:01<5:47:44, 1.06s/it, lr=1e-5, step_loss=0.158]Traceback (most recent call last): File "finetune.py", line 869, in main() File "finetune.py", line 799, in main encoder_hidden_states[clip_empty_idx] = empty_emb[clip_empty_idx] IndexError: The shape of the mask [7] at index 0 does not match the shape of the indexed tensor [8, 1536] at index 0

Hey @liuyangyu2003 were you able to solve this problem? Even I am facing similar issue.
